-- Phase 4: Framework Guide
-- HR-editable in-app performance framework reference

CREATE TABLE guide_sections (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        TEXT NOT NULL UNIQUE,
  title       TEXT NOT NULL,
  content     TEXT NOT NULL DEFAULT '',
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE guide_sections ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read
CREATE POLICY "guide_sections_authenticated_read"
  ON guide_sections
  FOR SELECT
  TO authenticated
  USING (true);

-- HR Admin can update content
CREATE POLICY "guide_sections_hradmin_update"
  ON guide_sections
  FOR UPDATE
  TO authenticated
  USING (private.is_hr_admin())
  WITH CHECK (private.is_hr_admin());

-- ───────────────────────────────────────────────────────────────────
-- Seed: 5 framework sections
-- ───────────────────────────────────────────────────────────────────

INSERT INTO guide_sections (slug, title, content, sort_order) VALUES

('company-values', 'Company Values', E'# Company Values\n\nBCOMM is built on seven core values that define how we work, grow, and deliver.\n\n## 1. Excellence\nWe hold ourselves to the highest standard in everything we produce. Good enough is never the goal — we push for great.\n\n## 2. Ownership\nWe take full responsibility for our work and its outcomes. We don''t wait to be asked; we identify what needs to be done and do it.\n\n## 3. Collaboration\nWe achieve more together than alone. We share knowledge openly, support each other through challenges, and celebrate shared wins.\n\n## 4. Integrity\nWe do what we say, say what we mean, and always act in the best interests of our clients, colleagues, and company.\n\n## 5. Curiosity\nWe stay hungry to learn. We question assumptions, explore new ideas, and embrace the discomfort of not knowing as the first step to growth.\n\n## 6. Adaptability\nWe thrive in change. We treat setbacks as feedback and adjust quickly to new information, markets, and opportunities.\n\n## 7. AI Builder Mindset\nWe actively build, experiment with, and integrate AI tools into our work. This is not optional — it is a core professional competency at BCOMM. Every team member is expected to have at least one active AI project or AI-enhanced workflow at all times.', 1),

('checkin-structure', 'Monthly Check-in Structure', E'# Monthly Check-in Structure\n\nMonthly check-ins are the heartbeat of the BCOMM performance system. They happen in two phases: **employee pre-meeting** and **manager post-meeting**.\n\n## Employee Pre-Meeting Section\n\nCompleted by the employee before the 1:1 meeting.\n\n### Most Important Things (MITs)\nList up to three MITs for the current month. Each MIT should have:\n- **Title** — a concise name for the initiative or goal\n- **Description** — context, success criteria, or current status\n\n### Reflections\n- **What went well?** — Wins, successes, moments of high performance\n- **What would I do differently?** — Areas for growth, mistakes turned into lessons\n- **Support requests** — What do you need from your manager or the wider team?\n\n### AI Builder\nDescribe your current AI project or AI-enhanced workflow. This field is **required to submit** your check-in and reflects the AI Builder Mindset value.\n\n---\n\n## Manager Post-Meeting Section\n\nCompleted by the manager after the 1:1 meeting.\n\n### MIT Notes\nManager''s observations and context on the employee''s MITs.\n\n### Feedback\n- **What they did well** — Manager''s perspective on wins\n- **What they should do differently** — Constructive, forward-looking guidance\n- **Support commitments** — What will the manager do to help?\n\n### Agreed Next Month''s MITs\nManager and employee agree on up to three MITs for the coming month. These are set collaboratively, not unilaterally.', 2),

('scoring-definitions', 'Scoring Definitions', E'# Quarterly Scoring Definitions\n\nEach quarter, managers score direct reports across three components on a 1–5 scale.\n\n## Score Scale\n\n| Score | Label | What it means |\n|-------|-------|---------------|\n| 1 | Significantly below expectations | Performance is well below the bar; urgent action plan required |\n| 2 | Below expectations | Performance falls short in meaningful ways; improvement needed |\n| 3 | Meets expectations | Solid, reliable performance at the expected level |\n| 4 | Exceeds expectations | Consistently performs above the standard; a strong contributor |\n| 5 | Outstanding | Exceptional impact; a role model for the team |\n\n---\n\n## The Three Components\n\n### Professional Mastery\nTechnical skills, domain knowledge, and craft quality. Measures how well the individual applies their expertise to their work. Includes depth of knowledge, quality of output, speed of skill development, and ability to solve complex problems.\n\n### OKRs / Stretch Goals\nProgress and outcomes on committed OKRs and stretch objectives for the quarter. Measures ambition, follow-through, and results. Not just "did they complete their OKRs" but "did they set meaningful goals and push hard on them?"\n\n### Behaviours / Values\nHow the individual embodies BCOMM''s seven values in day-to-day work. Includes collaboration, communication, ownership, integrity, and — critically — **AI Builder Mindset**.\n\n> **AI Builder Gate**: If a team member does not have an active AI project or AI-enhanced workflow this quarter, the Behaviours/Values score has a minimum floor of **4**. A score of 1, 2, or 3 is only available when the AI Builder checkbox is confirmed active.\n\n---\n\n## Annual Roll-Up\n\nAnnual scores are the average of all completed quarterly scores. Managers may override the suggested annual score with a written rationale. The final annual score is the single source of truth for year-end review conversations.', 3),

('role-expectations', 'Role Expectations', E'# Role Expectations\n\nLunarTrack has three user roles, each with distinct responsibilities in the performance system.\n\n## Employee\nEmployees are the primary participants in the performance cycle.\n\n**Responsibilities:**\n- Submit monthly check-ins before each 1:1 (pre-meeting section must be filled and submitted)\n- Draft and submit OKRs at the start of each quarter for manager approval\n- Keep the AI Builder field current — this is non-negotiable\n- Engage honestly in the reflection sections; this data is for growth, not evaluation\n- Review and act on manager feedback and agreed next-month MITs\n\n**Cannot:**\n- See another employee''s check-ins or OKRs\n- Access manager scoring until HR Admin unlocks visibility\n- Edit the manager''s post-meeting section\n\n---\n\n## Manager\nManagers run the performance cycle for their direct reports.\n\n**Responsibilities:**\n- Review and complete the post-meeting section within 48 hours of each 1:1\n- Review submitted OKRs promptly — approve or request revisions with context\n- Complete the quarterly OKR review for each direct report at end of quarter\n- Score each direct report quarterly across three components\n- Finalize annual scores with honest assessment and override rationale where applicable\n\n**Access:**\n- Can see all check-ins for direct reports (post-employee submission)\n- Can see all OKRs across their reporting subtree\n- Cannot see check-ins or OKRs of employees outside their subtree\n\n---\n\n## HR Admin\nHR Admins manage the system and have full read access.\n\n**Responsibilities:**\n- Configure user roles and org structure\n- Create and manage performance periods\n- Toggle score visibility for employees\n- Keep this Framework Guide current\n\n**Access:**\n- Full read access to all records\n- Can update any guide section inline', 4),

('ai-builder-mindset', 'AI Builder Mindset', E'# AI Builder Mindset\n\nAI Builder Mindset is the seventh BCOMM value and the one most directly tied to the performance system.\n\n## What It Means\n\nBCOMM believes that every professional — regardless of role — should be actively experimenting with, building, and integrating AI into their work. This is not a "nice to have." It is a core expectation for continued growth at the company.\n\nAn **active AI project** means you are:\n- Building a tool, workflow, or prototype that uses AI\n- Meaningfully integrating an AI assistant into your daily work in a way that improves output quality or speed\n- Learning and applying a new AI capability — and sharing what you''ve learned\n\n## How It Appears in the Performance System\n\n### Monthly Check-in\nThe AI Builder field is the final section of your monthly check-in and is **required before submission**. Use it to describe what AI tool or project you are currently working on or experimenting with.\n\n### Quarterly OKR Review\nThe quarterly OKR review includes an **AI Builder Active** checkbox. Your manager will confirm whether you had an active AI project this quarter based on your check-in responses.\n\n### Quarterly Scoring Gate\nIf the AI Builder checkbox is **not** checked for a quarter, the **Behaviours/Values score is floored at 4**. Scores of 1, 2, or 3 are only available when AI Builder is confirmed active. This is by design — a low Behaviours/Values score can only be assigned to someone who is fully engaged with the AI Builder expectation.\n\n## Why This Matters\n\nThe world is changing fast. BCOMM''s competitive edge depends on our people being ahead of the curve on AI — not observers, but practitioners. The performance system exists to make this expectation concrete, measurable, and rewarded.', 5);
